### ISSUE TITLE
[Typo] in failure_screen filename

### ISSUE THREAD

**Issue by Tobivaria** [Robert-Brunhage-Organization/movie_recommendation_app_course#1]
Hi Robert,

you "faied", as there's a typo in the following filename 😀  :
`movie_recommendation_app_course/lib/core/widgets/faiure_screen.dart`

Since you want to have everything in one commit, I did not open a pull request

Best
Tobi

**Comment by RobertBrunhage** [comment]
Oh sorry for seeing it a bit late, I have it fixed!

Thanks 🔥
