### ISSUE TITLE
Slider divisions

### ISSUE THREAD

**Issue by flyby3d** [Robert-Brunhage-Organization/movie_recommendation_app_course#2]
Lecture 6: rating_screen.dart

The number of divisions in the slider for a range 1-10 should be 9 ?

**Comment by RobertBrunhage** [comment]
You are correct!

https://github.com/Robert-Brunhage-Organization/movie_recommendation_app_course/blob/2b75038d486d6fa352475f91df262cfbd3cd99b4/lib/features/movie_flow/rating/rating_screen.dart#L61

Fixed in the code now, sorry for the slow response!
